package com.admitone.model.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * An entity User composed by 4 fields (id, userName, pwd, orders). The Entity
 * annotation indicates that this class is a JPA entity. The Table annotation
 * specifies the name for the table in the db which is embedded h2.
 *
 * @author yyan
 */
@Entity
@Table(name = "users", indexes = {@Index(name = "user_name_idx",  columnList="userName", unique = true)})
public class User implements Serializable {
	// Notice that Hibernate generates columns in alphabetical order

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	// Checks whether the value is not null nor empty, trimming the value first.
	// It means that, it won’t allow just empty spaces
	@NotBlank
	@JsonIgnore
	private String pwd;

	@NotBlank
	@Email
//	@Column(unique = true)
	private String userName;

	// The mappedBy was used to define the Call entity as the relationship
	// owner.
	// Being the relationship owner is nothing more than to have the foreign key
	// in the database table
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
//	private Collection<Order> orders;

	public User() {
	}

	public User(long id) {
		this.id = id;
	}

	public User(String userName, String pwd) {
		this.userName = userName;
		this.pwd = pwd;
	}
	
	public User(long id, String userName, String pwd) {
		this.id = id;
		this.userName = userName;
		this.pwd = pwd;
	}

	// Getter and setter methods
	// No setId
	public long getId() {
		return id;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPwd() {
		return pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

}
